name: Build and Release Vendored Gemfile

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    if: github.repository_owner == 'joernio'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get next release version (dry run)
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true

      - name: Show next version
        env:
          CURR_TAG: ${{ steps.taggerDryRun.outputs.tag }}"
          NEW_TAG: ${{ steps.taggerDryRun.outputs.new_tag }}
        run: |
          echo "The next tag version will be: $NEW_TAG"
          echo "The current tag is: $CURR_TAG"
          ./update_version.rb $NEW_TAG

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.5
          bundler-cache: false

      - name: Bundle and install dependencies
        run: |
          bundle config set frozen false
          bundle install --path=vendor/bundle

      - name: Build distribution and set Git perms
        run: |
          sudo chown -R "${USER:-$(id -un)}" .
          gem build ruby_ast_gen.gemspec

      - name: Add and commit updated files holding version information
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: |
            lib/ruby_ast_gen/version.rb
            Gemfile.lock
          commit_message: Update VERSION file

      - name: Upload vendored distribution to GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN_PERMISSIONS: "read:packages, write:packages"
        with:
          tag_name: ${{ steps.taggerDryRun.outputs.new_tag }}
          files: ruby_ast_gen-*.gem
